# Generated by Django 5.2.4 on 2025-07-30 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoilCropRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soil_type', models.CharField(max_length=50)),
                ('crop_name', models.CharField(max_length=100)),
                ('priority', models.IntegerField()),
            ],
            options={
                'db_table': 'soil_crop_recommendation',
            },
        ),
        migrations.AlterModelTable(
            name='cropsoilirrigation',
            table='crop_soil_irrigation',
        ),
    ]
