# Generated by Django 5.2.4 on 2025-07-30 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmbot', '0002_soilcroprecommendation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropDuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=100)),
                ('duration_min_days', models.IntegerField()),
                ('duration_max_days', models.IntegerField()),
            ],
        ),
    ]
