# Generated by Django 5.2.4 on 2025-08-03 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmbot', '0003_cropduration'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantingCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('planting_start_month', models.CharField(max_length=20)),
                ('planting_end_month', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'planting_calendar',
            },
        ),
    ]
